name: install-and-test-workflow

on: [push]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install '.[dev]' --index-url https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple
        pip install coverage coveralls
    - name: Test with pytest
      run: |
        python -m coverage run -m pytest -sv
    - name: Submit to coveralls
      continue-on-error: true
      env:
        GITHUB_TOKEN: {% raw -%}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      run: |
        coveralls --service=github

  build-and-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Build the package
      run: |
        pip install --upgrade pip
        pip install build
        python -m build --sdist
    - name: Install the package
      run: |
        pip install dist/*.tar.gz --index-url https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple

  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check .
      # Uncomment the following line to enable format check
      # - run: ruff format .
